services:
  app:
    build:
      context: .

    env_file:
      - .env

    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"

    volumes:
      - ./:/app

    command: >
      sh -c "python odoo-bin -c odoo.conf -i base"

    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine3.17

    restart: always

    env_file:
      - .env

    ports:
      - "5432:5432"

    volumes:
      - my_db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  my_db:
